server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/fish_helper?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
    password: root
    username: root


